AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack for workshop environment
Parameters:

  Username:
    Type: String
    Description: Username for IAM user and notebook

  NotebookLifecycleConfig:
    Type: String
    Description: The lifecycle config

  ManagedPolicyArn:
    Type: String
    Description: ARN of the managed policy to attach to the IAM user

Resources:

  WorkshopUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${Username}-notebook-control-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: !Sub arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:notebook-instance/${Username}-notebook
            Action:
              - sagemaker:CreatePresignedNotebookInstanceUrl
              - sagemaker:DescribeNotebookInstance
              - sagemaker:StartNotebookInstance
              - sagemaker:StopNotebookInstance
              - sagemaker:ListTags
          - Effect: Allow
            Resource: '*'
            Action:
              - sagemaker:ListNotebookInstances
              - sagemaker:ListCodeRepositories
              - sagemaker:ListNotebookInstanceLifecycleConfigs
              - sagemaker:DescribeNotebookInstanceLifecycleConfig

  WorkshopUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Username
      ManagedPolicyArns:
        - !Ref WorkshopUserPolicy
        - !Ref ManagedPolicyArn

  NotebookPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub Notebook-policy-${Username}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
              - logs:*
              - ec2:Describe*
              - iam:PassRole
            Resource: '*'
          - Effect: Allow
            Resource: !Sub arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:notebook-instance/${Username}-notebook
            Action:
              - sagemaker:DescribeNotebookInstance
              - sagemaker:StopNotebookInstance
              - sagemaker:ListTags
          - Effect: Allow
            Resource: '*'
            Action:
              - sagemaker:ListNotebookInstances
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParameterHistory
              - ssm:GetParametersByPath
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Username}/*

  WorkshopNotebookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Ref ManagedPolicyArn
        - !Ref NotebookPolicy

  WorkshopNotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Sub ${Username}-notebook
      InstanceType: ml.t3.medium
      RoleArn: !GetAtt WorkshopNotebookRole.Arn
      LifecycleConfigName: !Ref NotebookLifecycleConfig
      DefaultCodeRepository: https://github.com/xebia/aws-prompt-engineering-workshop
      Tags:
        - Key: Username
          Value: !Ref Username

  BedrockPrompt:
    Type: AWS::Bedrock::Prompt
    Properties:
      Name: !Sub ${Username}-prompt
      Description: !Sub "Prompt used for the workshop user: ${Username}"
      DefaultVariant: production
      Variants:
        - Name: production
          TemplateType: TEXT
          TemplateConfiguration:
            Text:
              Text: Hello {{customer_name}}, welcome to our support. How can I help you with {{issue_type}} today?
              CachePoint:
                Type: default
              InputVariables:
                - Name: customer_name
                - Name: issue_type
          ModelId: eu.amazon.nova-lite-v1:0
          InferenceConfiguration:
            Text:
              MaxTokens: 1024
              Temperature: 0.7
              TopP: 0.9
#              StopSequences: []

  BedrockPromptVersion:
    Type: AWS::Bedrock::PromptVersion
    Properties:
      PromptArn: !GetAtt BedrockPrompt.Arn

  ManagedPromptSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Username}/managed-prompt
      Type: String
      Value: !GetAtt BedrockPromptVersion.Arn
