AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack for workshop environment
Parameters:

  Username:
    Type: String
    Description: Username for IAM user and notebook

  NotebookLifecycleConfig:
    Type: String
    Description: The lifecycle config

  ManagedPolicyArn:
    Type: String
    Description: ARN of the managed policy to attach to the IAM user

Resources:

  WorkshopNotebookPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${Username}-notebook-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: !Sub arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:notebook-instance/${Username}-notebook
            Action:
              - sagemaker:CreatePresignedNotebookInstanceUrl
              - sagemaker:DescribeNotebookInstance
              - sagemaker:StartNotebookInstance
              - sagemaker:StopNotebookInstance
              - sagemaker:ListTags
          - Effect: Allow
            Resource: '*'
            Action:
              - sagemaker:ListNotebookInstances
              - sagemaker:ListCodeRepositories
              - sagemaker:ListNotebookInstanceLifecycleConfigs
              - sagemaker:DescribeNotebookInstanceLifecycleConfig

  WorkshopUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Username
      ManagedPolicyArns:
        - !Ref WorkshopNotebookPolicy
        - !Ref ManagedPolicyArn
        - !Ref WorkshopGuardrailPolicy
        - !Ref WorkshopPromptManagementPolicy

  NotebookPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub Notebook-policy-${Username}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
              - logs:*
              - ec2:Describe*
              - iam:PassRole
            Resource: '*'
          - Effect: Allow
            Resource: !Sub arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:notebook-instance/${Username}-notebook
            Action:
              - sagemaker:DescribeNotebookInstance
              - sagemaker:StopNotebookInstance
              - sagemaker:ListTags
          - Effect: Allow
            Resource: '*'
            Action:
              - sagemaker:ListNotebookInstances
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParameterHistory
              - ssm:GetParametersByPath
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Username}/*
          - Effect: Allow
            Action:
              - bedrock:ApplyGuardrail
            Resource:
              - !GetAtt BedrockGuardrail.GuardrailArn
              - !Sub arn:aws:bedrock:*:${AWS::AccountId}:guardrail-profile/eu.guardrail.v1:0
          - Effect: Allow
            Action:
              - bedrock:RenderPrompt
            Resource:
              - !Sub arn:aws:bedrock:*:${AWS::AccountId}:prompt/*
              - !Sub arn:aws:bedrock:*:${AWS::AccountId}:prompt/*:*

  WorkshopNotebookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Ref ManagedPolicyArn
        - !Ref NotebookPolicy

  WorkshopNotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Sub ${Username}-notebook
      InstanceType: ml.t3.medium
      RoleArn: !GetAtt WorkshopNotebookRole.Arn
      LifecycleConfigName: !Ref NotebookLifecycleConfig
      DefaultCodeRepository: https://github.com/xebia/aws-prompt-engineering-workshop
      Tags:
        - Key: Username
          Value: !Ref Username

  BedrockPrompt:
    Type: AWS::Bedrock::Prompt
    Properties:
      Name: !Sub ${Username}-prompt
      Description: !Sub "Prompt used for the workshop user: ${Username}"
      DefaultVariant: production
      Variants:
        - Name: production
          TemplateType: TEXT
          TemplateConfiguration:
            Text:
              Text: |
                You are a customer support assistant specialized in summarizing chat transcripts between customers and agents.
                Your goal is to provide a concise, structured summary that captures:
                  - The customerâ€™s main issue
                  - The troubleshooting steps taken
                  - The final resolution (or next steps)

                Use the following style:
                  - Tone: Neutral and professional
                  - Format: Markdown bullet points
                  - Length: â‰¤ 150 words

                ---

                ðŸ§¾ **Customer Chat Transcript:**
                {{chat_transcript}}

                ðŸ“š **Reference Knowledge Base:**
                {{knowledge_base}}
              CachePoint:
                Type: default
              InputVariables:
                - Name: chat_transcript
                - Name: knowledge_base
          ModelId: !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/eu.amazon.nova-lite-v1:0
          InferenceConfiguration:
            Text:
              MaxTokens: 1024
              Temperature: 0.7
              TopP: 0.9
#              StopSequences: []

  BedrockPromptVersion:
    Type: AWS::Bedrock::PromptVersion
    Properties:
      PromptArn: !GetAtt BedrockPrompt.Arn

  ManagedPromptSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Username}/managed-prompt
      Type: String
      Value: !GetAtt BedrockPromptVersion.Arn

  BedrockGuardrail:
    Type: AWS::Bedrock::Guardrail
    Properties:
      Name: !Sub ${Username}-guardrail
      Description: !Sub "Guardrail for workshop user: ${Username}"
      BlockedInputMessaging: The given prompt has been blocked by Amazon Bedrock Guardrails.
      BlockedOutputsMessaging: The prompt generated by the LLM has been blocked by Amazon Bedrock Guardrails.
      CrossRegionConfig:
        GuardrailProfileArn: !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:guardrail-profile/eu.guardrail.v1:0
      ContentPolicyConfig:
        ContentFiltersTierConfig:
          TierName: STANDARD
        FiltersConfig:
          - InputAction: BLOCK
            InputEnabled: true
            InputModalities:
              - TEXT
            InputStrength: MEDIUM
            OutputAction: BLOCK
            OutputEnabled: true
            OutputModalities:
              - TEXT
            OutputStrength: MEDIUM
            Type: SEXUAL
          - InputAction: BLOCK
            InputEnabled: true
            InputModalities:
              - TEXT
            InputStrength: MEDIUM
            OutputAction: BLOCK
            OutputEnabled: true
            OutputModalities:
              - TEXT
            OutputStrength: MEDIUM
            Type: VIOLENCE
          - InputAction: BLOCK
            InputEnabled: true
            InputModalities:
              - TEXT
            InputStrength: MEDIUM
            OutputAction: BLOCK
            OutputEnabled: true
            OutputModalities:
              - TEXT
            OutputStrength: MEDIUM
            Type: HATE
          - InputAction: BLOCK
            InputEnabled: true
            InputModalities:
              - TEXT
            InputStrength: MEDIUM
            OutputAction: BLOCK
            OutputEnabled: true
            OutputModalities:
              - TEXT
            OutputStrength: MEDIUM
            Type: INSULTS
          - InputAction: BLOCK
            InputEnabled: true
            InputModalities:
              - TEXT
            InputStrength: MEDIUM
            OutputAction: BLOCK
            OutputEnabled: true
            OutputModalities:
              - TEXT
            OutputStrength: MEDIUM
            Type: MISCONDUCT
          - InputAction: BLOCK
            InputEnabled: true
            InputModalities:
              - TEXT
            InputStrength: MEDIUM
            OutputAction: BLOCK
            OutputEnabled: true
            OutputModalities:
              - TEXT
            OutputStrength: NONE
            Type: PROMPT_ATTACK

  BedrockGuardrailVersion:
    Type: AWS::Bedrock::GuardrailVersion
    Properties:
       GuardrailIdentifier: !GetAtt BedrockGuardrail.GuardrailId

  GuardrailIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Username}/guardrail-id
      Type: String
      Value: !GetAtt BedrockGuardrailVersion.GuardrailId

  GuardrailVersionSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Username}/guardrail-version
      Type: String
      Value: !GetAtt BedrockGuardrailVersion.Version

  WorkshopGuardrailPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${Username}-guardrail-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - bedrock:CreateGuardrailVersion
              - bedrock:UpdateGuardrail
              - bedrock:GetGuardrail
              - bedrock:ListTagsForResource
            Resource:
              - !GetAtt BedrockGuardrail.GuardrailArn
              - !Sub ${BedrockGuardrail.GuardrailArn}/*
              - !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:guardrail-profile/eu.guardrail.v1:0
          - Effect: Allow
            Action:
              - bedrock:ListMarketplaceModelEndpoints
              - bedrock:ListGuardrails
              - bedrock:ListFoundationModels
              - bedrock:GetUseCaseForModelAccess
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - sagemaker:ListHubContents
            Resource:
              - !Sub arn:aws:sagemaker:${AWS::Region}:aws:hub/SageMakerPublicHub
          - Effect: Allow
            Action:
              - bedrock:List*
            Resource: '*'

  WorkshopPromptManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${Username}-prompt-management-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - bedrock:ListPrompts
              - bedrock:OptimizePrompt
          - Effect: Allow
            Resource:
              - !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:prompt/*
            Action:
              - bedrock:GetPrompt
              - bedrock:RenderPrompt
              - bedrock:UpdatePrompt
          - Effect: Allow
            Resource:
              - !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/eu.amazon.nova-lite-v1:0
            Action:
              - bedrock:GetInferenceProfile
